name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment for deployment
        required: true
        type: choice
        options:
          - rubik

jobs:
  build:
    runs-on: ubuntu-20.04 # matching rubik
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: lila-push
          path: target/release/lila-push
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    concurrency:
      group: ${{ inputs.environment }}
    needs: build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: lila-push
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy-host
            HostName $SSH_HOST
            User $SSH_USER
            HostKey "$SSH_HOST_KEY"
            IdentityFile ~/.ssh/deploy.key
            ForwardAgent no
          END
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST_KEY: ${{ secrets.SSH_HOST_KEY }}
      - name: Deploy via SSH
        run: cat lila-push | ssh deploy-host "mv /usr/local/bin/lila-push /usr/local/bin/lila-push.bak && cat - > /usr/local/bin/lila-push && chmod +x /usr/local/bin/lila-push && systemctl restart lila-push"
